module.exports = [
    {
        title: "Llama Amigurumi",
        name: "Alex P",
        image: ["https://i.imgur.com/QR91hnN.jpg","https://i.imgur.com/R6BoNQw.jpg"],
        type: "Crochet",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt.",
        links:["https://www.instagram.com/craftsknitoys/","https://www.youtube.com/playlist?list=PLqKKxGCteJVz6Bm-8Zp4ARf0JcCPuB292"]
    },{
        title: "Conrad the Crocodile",
        name: "Alex P",
        image: ["https://i.imgur.com/elHLPAE.jpg","https://i.imgur.com/KyI4Otj.jpg"],
        type: "Crochet",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt.",
        links:["https://www.etsy.com/listing/246003846/amigurumi-pattern-conrad-the-crocodile?","http://ildikko-crochet.com/patterns/"]
    }
]