module.exports = [
    {
        title: "Some Title",
        name: "John Doe",
        image: "https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bGVuc3xlbnwwfHwwfHw%3D&w=1000&q=80",
        type: "Photography",
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat blanditiis fuga id hic explicabo molestiae debitis quia, molestias repudiandae in facilis ab iusto ut temporibus distinctio quidem officia ipsum incidunt.",
        links:["https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bGVuc3xlbnwwfHwwfHw%3D&w=1000&q=80","https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bGVuc3xlbnwwfHwwfHw%3D&w=1000&q=80","https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bGVuc3xlbnwwfHwwfHw%3D&w=1000&q=80","https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bGVuc3xlbnwwfHwwfHw%3D&w=1000&q=80"]
    }
]